### ISSUE TITLE
异步加载的title能被seo爬到吗？

### ISSUE THREAD

**Issue by yasinshaw** [monkeyWangs/vue-meta-info#2]
如题，比如我有一个“文章”页面，其标题和关键词、作者等信息需要从后端异步加载，再把它放到title和meta标签里，请问这样的异步加载能被SEO爬取到吗？

**Comment by monkeyWangs** [comment]
不可以，这样需要使用服务端渲染。

**Comment by yasinshaw** [comment]
谢谢回答！
