### ISSUE TITLE
异步加载 meta 设置失败

### ISSUE THREAD

**Issue by sugerss** [monkeyWangs/vue-meta-info#3]
@monkeyWangs 
![image](https://user-images.githubusercontent.com/30251445/33169067-2cd46ee4-d07e-11e7-89f8-a3c6dfea00ce.png)

**Comment by monkeyWangs** [comment]
应该没问题吧？ 报错了还是说没设置成功？

**Comment by sugerss** [comment]
并没有报错。title是设置成功的，但是meta标签是失败的，所以我有想了解一下是不是格式有问题呢？

**Comment by monkeyWangs** [comment]
您好，格式上是对的。我也尝试按照您这种写法，也是可以成功的，具体的有空我这边再看一下

**Comment by sugerss** [comment]
您好，我又重新看了一下代码，有一个警告，‘Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.’，但是呢
![image](https://user-images.githubusercontent.com/30251445/33522972-86e80af8-d835-11e7-8577-bec8b1eeb110.png)，
，不太明白它们之间有什么联系


’
