### ISSUE TITLE
使用VUE-SSR渲染，采用vue-meta-info的一些异常

### ISSUE THREAD

**Issue by dandan888111** [monkeyWangs/vue-meta-info#5]
1、新增加的meta标签，在源码里找不到，只能在F12里看到，且老的mata不会被删除，F12里会出现新、老两份mata，没有达到SEO的目的。
2、title设置后，源码里的title也不会更新，页头的标题会更新，没有达到SEO的目的。

**Comment by monkeyWangs** [comment]
已发布```npm 0.1.5```支持ssr。建议更新: ```npm i vue-meta-info@0.1.5```
